services:
  nexus-desktop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce@sha256:dc752c7ac78278e39b5cd32e85cbfe7cfc7f68c32f03f06bf91bcb1af1b7737d
    container_name: nexus-desktop
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TITLE: ${TITLE:-Nexus Desktop}
    volumes:
      - /DATA/Nexus/Home:/config
      - /DATA/Nexus/Workspace:/config/Workspace
      - /DATA/Nexus/Downloads:/config/Downloads
      - /DATA/Nexus/Shared:/config/Shared
    ports:
      - "6901:3001"
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - nexus-network

networks:
  nexus-network:
    external: true
